markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: false
auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
domain: archstory.github.io
title: archstory 
description: c, avr, embedded, Linux, python ...
author: archstory
email: daniel900421@iclud.com
github: archstory

config:
  js_dir:
  img_dir:
  css_dir:
