markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: wdyggh.github.io
title: wdyggh's Blog
description: c, avr, raspberryPi, Linux, reading...
author: wdy
email: wdyggh@gmail.com
github: wdyggh

config:
  js_dir:
  img_dir:
  css_dir:
